### ISSUE TITLE
Permutation Instruction Modification

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto-ref#3]
Somewhere to track changes to the reference XCrypto implementation pertaining to scarv/xcrypto-spec#22

**Todo:**
- [x] Decoder:
  - [x] Remove `xc.pperm.*` decode lines
  - [x] Add `bmv`, `pbit`, `ipbit` and `pbyte` decode lines
  - [x] Rename `twiddle` instruction class to `permute`, using it to referr to the `pbit`,`ipbit`,`pbyte` instructions.
  - [x] Put `bmv` in the bitwise class with `ins` and `ext`
- [x] Permute FU
  - [x] Add a new functional unit which implements only the `permute` instruction class.
- [x] Packed ALU
  - [x] Remove `xc.pperm.*` implementations
  - [x] Add `bmv` implementation.

**Comment by ben-marshall** [comment]
**Pre-modification implementation statistics:**

- Post Synthesis Utilisation:
```
+----------------------------+------+-------+-----------+-------+
|          Site Type         | Used | Fixed | Available | Util% |
+----------------------------+------+-------+-----------+-------+
| Slice LUTs*                | 7658 |     0 |    101400 |  7.55 |
| Slice Registers            | 1615 |     0 |    202800 |  0.80 |
| F7 Muxes                   |  328 |     0 |     50700 |  0.65 |
| F8 Muxes                   |  101 |     0 |     25350 |  0.40 |
+----------------------------+------+-------+-----------+-------+
```

- Post implementation timing at 100MHz:
  - WNS: -0.557ns
  - TNS: -110.337ns
  - TFP: 498

**Comment by ben-marshall** [comment]
**Post `xc.pperm` removal implementation statistics:**

- Post Synthesis Utilisation:
```
+----------------------------+------+-------+-----------+-------+
|          Site Type         | Used | Fixed | Available | Util% |
+----------------------------+------+-------+-----------+-------+
| Slice LUTs*                | 7584 |     0 |    101400 |  7.48 |
| Slice Registers            | 1612 |     0 |    202800 |  0.79 |
| F7 Muxes                   |  176 |     0 |     50700 |  0.35 |
| F8 Muxes                   |   32 |     0 |     25350 |  0.13 |
+----------------------------+------+-------+-----------+-------+
```

- Post implementation timing at 100MHz:
  - WNS: -0.290ns
  - TNS: -21.046ns
  - TFP: 218

**Comment by ben-marshall** [comment]
**Post `xc.bmv` implementation statistics:**

`xc.ipbit`,`xc.pbit` and `xc.pbyte` are un-implemented at this point.

- Post Synthesis Utilisation:
```
+----------------------------+------+-------+-----------+-------+
|          Site Type         | Used | Fixed | Available | Util% |
+----------------------------+------+-------+-----------+-------+
| Slice LUTs*                | 7542 |     0 |    101400 |  7.44 |
| Slice Registers            | 1618 |     0 |    202800 |  0.80 |
| F7 Muxes                   |  276 |     0 |     50700 |  0.54 |
| F8 Muxes                   |  102 |     0 |     25350 |  0.40 |
+----------------------------+------+-------+-----------+-------+
```

- Post implementation timing at 100MHz:
  - WNS: -0.030ns
  - TNS: -.213ns
  - TFP: 11

This is *not* how I expected things to go! Everything got smaller and faster. Need to be careful going forward. Formal proofs are passing though.

**Comment by ben-marshall** [comment]
**Post `xc.ipbit`,`xc.pbit` implementation statistics:**

`xc.pbyte` is un-implemented at this point.

- Post Synthesis Utilisation:
```
+----------------------------+------+-------+-----------+-------+
|          Site Type         | Used | Fixed | Available | Util% |
+----------------------------+------+-------+-----------+-------+
| Slice LUTs*                | 7774 |     0 |    101400 |  7.67 |
| Slice Registers            | 1613 |     0 |    202800 |  0.80 |
| F7 Muxes                   |  274 |     0 |     50700 |  0.54 |
| F8 Muxes                   |  102 |     0 |     25350 |  0.40 |
+----------------------------+------+-------+-----------+-------+
```

- Post implementation timing at 100MHz:
  - WNS: -0.251ns
  - TNS: -24.018ns
  - TFP: 212

**Comment by ben-marshall** [comment]
**Post implementation statistics:**

All permutation instruction removals and additions complete.

- Post Synthesis Utilisation:
```
+----------------------------+------+-------+-----------+-------+
|          Site Type         | Used | Fixed | Available | Util% |
+----------------------------+------+-------+-----------+-------+
| Slice LUTs*                | 7758 |     0 |    101400 |  7.65 |
| Slice Registers            | 1614 |     0 |    202800 |  0.80 |
| F7 Muxes                   |  273 |     0 |     50700 |  0.54 |
| F8 Muxes                   |  102 |     0 |     25350 |  0.40 |
+----------------------------+------+-------+-----------+-------+
```

- Post implementation timing at 100MHz:
  - WNS: -0.165ns
  - TNS: -7.117ns
  - TFP: 113
